### ISSUE TITLE
Non-ascii characters are not rendered

### ISSUE THREAD

**Issue by ragesoss** [Abbe98/articles-by-lat-lon-without-images-service#1]
Hi! I just found this tool and I'm excited to use it, since it seems to do the best job I've seen of identifying articles that are actually in need of photos. I'm trying to make a Pebble app that will let you know when you're near something that needs a photo.

It'd be great if this service handled character encoding in article titles. If it returns things like `"title":"Fj\u00e4llsk\u00e4fte"` (from the example url) then every consumer of the service will have to handle the re-encoding.

**Comment by Abbe98** [comment]
Hi! Exactly what I intended to use it for but not for the Pebble.

I will fix it this afternoon, thanks for reporting!

Let me know if there is anything else you will need :+1:

**Comment by Abbe98** [comment]
Okey, so the official Mediawiki API does not handle this type of charters so to remain compilable and not break existing applications I have introduced a optional `reencode` parameter. Append your requests with `&reencode=true` and the service will handle the encoding for you.

**Comment by ragesoss** [comment]
Wonderful! Thanks!
