### ISSUE TITLE
Add to Hay's tool directory

### ISSUE THREAD

**Issue by samwilson** [Abbe98/articles-by-lat-lon-without-images-service#2]
It'd be cool if this was listed in the tool directory: http://tools.wmflabs.org/hay/directory/

**Comment by Abbe98** [comment]
It's available, see: http://tools.wmflabs.org/hay/directory/#/author/Abbe98

If there is any change I could do in the description etc to make it more visible, let me know.

**Comment by samwilson** [comment]
Ah! Sorry!! :) I was searching for 'missing', and when I searched for 'images', I must have overlooked yours. I found http://tools.wmflabs.org/hay/directory/#/search/missing%20images and figured if I found one I'd found em all. :(
