### ISSUE TITLE
For Wikidata, negative coordinates are returned positive

### ISSUE THREAD

**Issue by ragesoss** [Abbe98/articles-by-lat-lon-without-images-service#6]
Compare the lon values of the results:
http://tools.wmflabs.org/articles-by-lat-lon-without-images/index.php?wiki=en&lat=47.6192935395824485&lon=-122.2857461742945&radius=2000&reencode=true

http://tools.wmflabs.org/articles-by-lat-lon-without-images/index.php?wiki=wikidata&lat=47.6192935395824485&lon=-122.2857461742945&radius=2000&reencode=true

**Comment by Abbe98** [comment]
Patching this tonight!

Note to self: make sure the regex for fetching lat/lon values allows `-`.

**Comment by Abbe98** [comment]
I have patched the code but not deployed it, currently it would break your temporary workaround, let me know when I can deploy it.

**Comment by ragesoss** [comment]
You can deploy. My workaround is not released.

**Comment by Abbe98** [comment]
Okey deploying now

**Comment by Abbe98** [comment]
...and deployed.
